services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


volumes:
  db_data:
  localstack_data: