// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_types.sql

package db

import (
	"context"
	"database/sql"
)

const archiveActivityType = `-- name: ArchiveActivityType :execrows
UPDATE activity_types
SET archived_at = NOW()
WHERE id = $1
  AND user_id = $2::bigint
  AND archived_at IS NULL
`

type ArchiveActivityTypeParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Archive instead of DELETE: report_entries keeps pointing to the item (ON DELETE RESTRICT).
func (q *Queries) ArchiveActivityType(ctx context.Context, arg ArchiveActivityTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveActivityType, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createActivityType = `-- name: CreateActivityType :one
INSERT INTO activity_types (user_id, code, label, tracks_quantity, quantity_unit, tracks_duration, position)
VALUES (
    $1::bigint,
    $2,
    $3,
    $4,
    $5,
    $6,
    (SELECT GREATEST(COALESCE(MAX(position), 0), 100) + 1
     FROM activity_types
     WHERE user_id = $1::bigint)
)
RETURNING id, user_id, code, label, tracks_quantity, quantity_unit, tracks_duration, position, archived_at, created_at
`

type CreateActivityTypeParams struct {
	UserID         int64          `json:"user_id"`
	Code           string         `json:"code"`
	Label          string         `json:"label"`
	TracksQuantity bool           `json:"tracks_quantity"`
	QuantityUnit   sql.NullString `json:"quantity_unit"`
	TracksDuration bool           `json:"tracks_duration"`
}

// Personal items are numbered after the standard ones: 101, 102...
func (q *Queries) CreateActivityType(ctx context.Context, arg CreateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRowContext(ctx, createActivityType,
		arg.UserID,
		arg.Code,
		arg.Label,
		arg.TracksQuantity,
		arg.QuantityUnit,
		arg.TracksDuration,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Label,
		&i.TracksQuantity,
		&i.QuantityUnit,
		&i.TracksDuration,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserActivityTypes = `-- name: GetUserActivityTypes :many
SELECT id, user_id, code, label, tracks_quantity, quantity_unit, tracks_duration, position, archived_at, created_at FROM activity_types
WHERE (user_id IS NULL OR user_id = $1::bigint)
  AND archived_at IS NULL
ORDER BY position, code
`

// Standard items (user_id IS NULL) + the user's own items, archived ones excluded.
func (q *Queries) GetUserActivityTypes(ctx context.Context, userID int64) ([]ActivityType, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivityTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityType{}
	for rows.Next() {
		var i ActivityType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Code,
			&i.Label,
			&i.TracksQuantity,
			&i.QuantityUnit,
			&i.TracksDuration,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isStandardActivityCode = `-- name: IsStandardActivityCode :one
SELECT EXISTS (
    SELECT 1 FROM activity_types
    WHERE user_id IS NULL AND code = $1
)
`

func (q *Queries) IsStandardActivityCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isStandardActivityCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateActivityType = `-- name: UpdateActivityType :one
UPDATE activity_types
SET code = $1,
    label = $2,
    quantity_unit = $3,
    position = COALESCE($4, position)
WHERE id = $5
  AND user_id = $6::bigint
  AND archived_at IS NULL
RETURNING id, user_id, code, label, tracks_quantity, quantity_unit, tracks_duration, position, archived_at, created_at
`

type UpdateActivityTypeParams struct {
	Code         string         `json:"code"`
	Label        string         `json:"label"`
	QuantityUnit sql.NullString `json:"quantity_unit"`
	Position     sql.NullInt32  `json:"position"`
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
}

// Only the user's own active item can change; standard items never match (user_id IS NULL).
// tracks_quantity / tracks_duration stay fixed: past entries were saved with them.
func (q *Queries) UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRowContext(ctx, updateActivityType,
		arg.Code,
		arg.Label,
		arg.QuantityUnit,
		arg.Position,
		arg.ID,
		arg.UserID,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Label,
		&i.TracksQuantity,
		&i.QuantityUnit,
		&i.TracksDuration,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
