// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authority.sql

package db

import (
	"context"
	"database/sql"
)

const createUserAuthority = `-- name: CreateUserAuthority :one
INSERT INTO authorities (first_name, last_name, phone_number, email, is_disciple_maker, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, first_name, last_name, phone_number, email, is_disciple_maker, created_at, user_id
`

type CreateUserAuthorityParams struct {
	FirstName       string         `json:"first_name"`
	LastName        sql.NullString `json:"last_name"`
	PhoneNumber     string         `json:"phone_number"`
	Email           sql.NullString `json:"email"`
	IsDiscipleMaker bool           `json:"is_disciple_maker"`
	UserID          int64          `json:"user_id"`
}

func (q *Queries) CreateUserAuthority(ctx context.Context, arg CreateUserAuthorityParams) (Authority, error) {
	row := q.db.QueryRowContext(ctx, createUserAuthority,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Email,
		arg.IsDiscipleMaker,
		arg.UserID,
	)
	var i Authority
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Email,
		&i.IsDiscipleMaker,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteAuthority = `-- name: DeleteAuthority :exec
DELETE FROM authorities
WHERE id = $1 AND user_id = $2
`

type DeleteAuthorityParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAuthority(ctx context.Context, arg DeleteAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuthority, arg.ID, arg.UserID)
	return err
}

const getAuthorityById = `-- name: GetAuthorityById :one
SELECT id, first_name, last_name, phone_number, email, is_disciple_maker, created_at, user_id
FROM authorities
WHERE user_id = $1 AND id = $2
LIMIT 1
`

type GetAuthorityByIdParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetAuthorityById(ctx context.Context, arg GetAuthorityByIdParams) (Authority, error) {
	row := q.db.QueryRowContext(ctx, getAuthorityById, arg.UserID, arg.ID)
	var i Authority
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Email,
		&i.IsDiscipleMaker,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserAuthorities = `-- name: GetUserAuthorities :many
SELECT id, first_name, last_name, phone_number, email, is_disciple_maker, created_at, user_id
FROM authorities
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2
OFFSET $3
`

type GetUserAuthoritiesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUserAuthorities(ctx context.Context, arg GetUserAuthoritiesParams) ([]Authority, error) {
	rows, err := q.db.QueryContext(ctx, getUserAuthorities, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Authority{}
	for rows.Next() {
		var i Authority
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Email,
			&i.IsDiscipleMaker,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
