// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_reports.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countReportedDays = `-- name: CountReportedDays :one
SELECT COUNT(*) FROM daily_reports
WHERE user_id = $1::bigint
  AND report_date BETWEEN $2::date AND $3::date
`

type CountReportedDaysParams struct {
	UserID   int64     `json:"user_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

func (q *Queries) CountReportedDays(ctx context.Context, arg CountReportedDaysParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportedDays, arg.UserID, arg.FromDate, arg.ToDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReportEntry = `-- name: CreateReportEntry :exec
INSERT INTO report_entries (report_id, activity_type_id, quantity, duration_minutes)
VALUES ($1, $2, $3, $4)
`

type CreateReportEntryParams struct {
	ReportID        int64         `json:"report_id"`
	ActivityTypeID  int64         `json:"activity_type_id"`
	Quantity        sql.NullInt32 `json:"quantity"`
	DurationMinutes sql.NullInt32 `json:"duration_minutes"`
}

func (q *Queries) CreateReportEntry(ctx context.Context, arg CreateReportEntryParams) error {
	_, err := q.db.ExecContext(ctx, createReportEntry,
		arg.ReportID,
		arg.ActivityTypeID,
		arg.Quantity,
		arg.DurationMinutes,
	)
	return err
}

const deleteReportEntries = `-- name: DeleteReportEntries :exec
DELETE FROM report_entries
WHERE report_id = $1
`

func (q *Queries) DeleteReportEntries(ctx context.Context, reportID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReportEntries, reportID)
	return err
}

const getDailyReport = `-- name: GetDailyReport :one
SELECT id, user_id, report_date, note, created_at, updated_at FROM daily_reports
WHERE user_id = $1 AND report_date = $2
`

type GetDailyReportParams struct {
	UserID     int64     `json:"user_id"`
	ReportDate time.Time `json:"report_date"`
}

func (q *Queries) GetDailyReport(ctx context.Context, arg GetDailyReportParams) (DailyReport, error) {
	row := q.db.QueryRowContext(ctx, getDailyReport, arg.UserID, arg.ReportDate)
	var i DailyReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReportDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyReportForm = `-- name: GetDailyReportForm :many
SELECT at.id AS activity_type_id, at.code, at.label, at.tracks_quantity, at.quantity_unit, at.tracks_duration,
       re.quantity, re.duration_minutes
FROM activity_types at
LEFT JOIN daily_reports dr ON dr.user_id = $1::bigint AND dr.report_date = $2::date
LEFT JOIN report_entries re ON re.report_id = dr.id AND re.activity_type_id = at.id
WHERE (at.user_id IS NULL OR at.user_id = $1::bigint)
  AND at.archived_at IS NULL
ORDER BY at.position, at.code
`

type GetDailyReportFormParams struct {
	UserID     int64     `json:"user_id"`
	ReportDate time.Time `json:"report_date"`
}

type GetDailyReportFormRow struct {
	ActivityTypeID  int64          `json:"activity_type_id"`
	Code            string         `json:"code"`
	Label           string         `json:"label"`
	TracksQuantity  bool           `json:"tracks_quantity"`
	QuantityUnit    sql.NullString `json:"quantity_unit"`
	TracksDuration  bool           `json:"tracks_duration"`
	Quantity        sql.NullInt32  `json:"quantity"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
}

// Every item the user can fill in, with the values entered that day (NULL when empty).
func (q *Queries) GetDailyReportForm(ctx context.Context, arg GetDailyReportFormParams) ([]GetDailyReportFormRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyReportForm, arg.UserID, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyReportFormRow{}
	for rows.Next() {
		var i GetDailyReportFormRow
		if err := rows.Scan(
			&i.ActivityTypeID,
			&i.Code,
			&i.Label,
			&i.TracksQuantity,
			&i.QuantityUnit,
			&i.TracksDuration,
			&i.Quantity,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportSummary = `-- name: GetReportSummary :many
WITH entries AS (
    SELECT re.activity_type_id, re.quantity, re.duration_minutes
    FROM report_entries re
    JOIN daily_reports dr ON dr.id = re.report_id
    WHERE dr.user_id = $1::bigint
      AND dr.report_date BETWEEN $2::date AND $3::date
)
SELECT at.id AS activity_type_id, at.code, at.label, at.quantity_unit, at.tracks_quantity, at.tracks_duration,
       COUNT(e.activity_type_id) AS days_count,
       COALESCE(SUM(e.quantity), 0)::bigint AS total_quantity,
       COALESCE(SUM(e.duration_minutes), 0)::bigint AS total_minutes
FROM activity_types at
LEFT JOIN entries e ON e.activity_type_id = at.id
WHERE (at.user_id IS NULL OR at.user_id = $1::bigint)
  AND at.archived_at IS NULL
GROUP BY at.id
ORDER BY at.position, at.code
`

type GetReportSummaryParams struct {
	UserID   int64     `json:"user_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type GetReportSummaryRow struct {
	ActivityTypeID int64          `json:"activity_type_id"`
	Code           string         `json:"code"`
	Label          string         `json:"label"`
	QuantityUnit   sql.NullString `json:"quantity_unit"`
	TracksQuantity bool           `json:"tracks_quantity"`
	TracksDuration bool           `json:"tracks_duration"`
	DaysCount      int64          `json:"days_count"`
	TotalQuantity  int64          `json:"total_quantity"`
	TotalMinutes   int64          `json:"total_minutes"`
}

// Totals per available item. The CTE keeps only this user's entries before the LEFT JOIN:
// standard items are shared, joining report_entries directly would mix users.
func (q *Queries) GetReportSummary(ctx context.Context, arg GetReportSummaryParams) ([]GetReportSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportSummary, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReportSummaryRow{}
	for rows.Next() {
		var i GetReportSummaryRow
		if err := rows.Scan(
			&i.ActivityTypeID,
			&i.Code,
			&i.Label,
			&i.QuantityUnit,
			&i.TracksQuantity,
			&i.TracksDuration,
			&i.DaysCount,
			&i.TotalQuantity,
			&i.TotalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyReportEntries = `-- name: ListDailyReportEntries :many
SELECT dr.report_date, dr.note,
       re.activity_type_id, at.code, at.label, at.quantity_unit, re.quantity, re.duration_minutes
FROM daily_reports dr
LEFT JOIN report_entries re ON re.report_id = dr.id
LEFT JOIN activity_types at ON at.id = re.activity_type_id
WHERE dr.user_id = $1::bigint
  AND dr.report_date BETWEEN $2::date AND $3::date
ORDER BY dr.report_date DESC, at.position, at.code
`

type ListDailyReportEntriesParams struct {
	UserID   int64     `json:"user_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type ListDailyReportEntriesRow struct {
	ReportDate      time.Time      `json:"report_date"`
	Note            sql.NullString `json:"note"`
	ActivityTypeID  sql.NullInt64  `json:"activity_type_id"`
	Code            sql.NullString `json:"code"`
	Label           sql.NullString `json:"label"`
	QuantityUnit    sql.NullString `json:"quantity_unit"`
	Quantity        sql.NullInt32  `json:"quantity"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
}

// History: one row per (day, entry). A day with only a note gives one row with NULL entry columns.
// Archived items still show here: past values are never lost.
func (q *Queries) ListDailyReportEntries(ctx context.Context, arg ListDailyReportEntriesParams) ([]ListDailyReportEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyReportEntries, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyReportEntriesRow{}
	for rows.Next() {
		var i ListDailyReportEntriesRow
		if err := rows.Scan(
			&i.ReportDate,
			&i.Note,
			&i.ActivityTypeID,
			&i.Code,
			&i.Label,
			&i.QuantityUnit,
			&i.Quantity,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyReport = `-- name: UpsertDailyReport :one
INSERT INTO daily_reports (user_id, report_date, note)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, report_date)
DO UPDATE SET note = EXCLUDED.note, updated_at = NOW()
RETURNING id, user_id, report_date, note, created_at, updated_at
`

type UpsertDailyReportParams struct {
	UserID     int64          `json:"user_id"`
	ReportDate time.Time      `json:"report_date"`
	Note       sql.NullString `json:"note"`
}

// Creates the day, or updates its note when it already exists.
func (q *Queries) UpsertDailyReport(ctx context.Context, arg UpsertDailyReportParams) (DailyReport, error) {
	row := q.db.QueryRowContext(ctx, upsertDailyReport, arg.UserID, arg.ReportDate, arg.Note)
	var i DailyReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReportDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
