// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hymns.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const createHymnBook = `-- name: CreateHymnBook :one
INSERT INTO hymn_books (code, title, language, position)
VALUES ($1, $2, $3, $4)
RETURNING id, code, title, language, position, created_at, updated_at
`

type CreateHymnBookParams struct {
	Code     string `json:"code"`
	Title    string `json:"title"`
	Language string `json:"language"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateHymnBook(ctx context.Context, arg CreateHymnBookParams) (HymnBook, error) {
	row := q.db.QueryRowContext(ctx, createHymnBook,
		arg.Code,
		arg.Title,
		arg.Language,
		arg.Position,
	)
	var i HymnBook
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Language,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHymnBook = `-- name: DeleteHymnBook :exec
DELETE FROM hymn_books
WHERE id = $1
`

func (q *Queries) DeleteHymnBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHymnBook, id)
	return err
}

const deleteHymnsNotIn = `-- name: DeleteHymnsNotIn :execrows
DELETE FROM hymns
WHERE book_id = $1
  AND NOT (number = ANY($2::int[]))
`

type DeleteHymnsNotInParams struct {
	BookID  int64   `json:"book_id"`
	Numbers []int32 `json:"numbers"`
}

func (q *Queries) DeleteHymnsNotIn(ctx context.Context, arg DeleteHymnsNotInParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHymnsNotIn, arg.BookID, pq.Array(arg.Numbers))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHymn = `-- name: GetHymn :one
SELECT number, title, author, parts FROM hymns
WHERE book_id = $1 AND number = $2
LIMIT 1
`

type GetHymnParams struct {
	BookID int64 `json:"book_id"`
	Number int32 `json:"number"`
}

type GetHymnRow struct {
	Number int32           `json:"number"`
	Title  string          `json:"title"`
	Author string          `json:"author"`
	Parts  json.RawMessage `json:"parts"`
}

func (q *Queries) GetHymn(ctx context.Context, arg GetHymnParams) (GetHymnRow, error) {
	row := q.db.QueryRowContext(ctx, getHymn, arg.BookID, arg.Number)
	var i GetHymnRow
	err := row.Scan(
		&i.Number,
		&i.Title,
		&i.Author,
		&i.Parts,
	)
	return i, err
}

const getHymnBookByCode = `-- name: GetHymnBookByCode :one
SELECT id, code, title, language, position, created_at, updated_at FROM hymn_books
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetHymnBookByCode(ctx context.Context, code string) (HymnBook, error) {
	row := q.db.QueryRowContext(ctx, getHymnBookByCode, code)
	var i HymnBook
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Language,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookHymns = `-- name: ListBookHymns :many
SELECT number, title, author, parts FROM hymns
WHERE book_id = $1
ORDER BY number
`

type ListBookHymnsRow struct {
	Number int32           `json:"number"`
	Title  string          `json:"title"`
	Author string          `json:"author"`
	Parts  json.RawMessage `json:"parts"`
}

func (q *Queries) ListBookHymns(ctx context.Context, bookID int64) ([]ListBookHymnsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookHymns, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookHymnsRow{}
	for rows.Next() {
		var i ListBookHymnsRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.Author,
			&i.Parts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymnBooks = `-- name: ListHymnBooks :many
SELECT b.id, b.code, b.title, b.language, b.position, b.updated_at,
       COUNT(h.id)::bigint AS hymn_count
FROM hymn_books b
LEFT JOIN hymns h ON h.book_id = b.id
GROUP BY b.id
ORDER BY b.position, b.title
`

type ListHymnBooksRow struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Title     string    `json:"title"`
	Language  string    `json:"language"`
	Position  int32     `json:"position"`
	UpdatedAt time.Time `json:"updated_at"`
	HymnCount int64     `json:"hymn_count"`
}

func (q *Queries) ListHymnBooks(ctx context.Context) ([]ListHymnBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listHymnBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHymnBooksRow{}
	for rows.Next() {
		var i ListHymnBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Language,
			&i.Position,
			&i.UpdatedAt,
			&i.HymnCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymnNumbers = `-- name: ListHymnNumbers :many
SELECT number FROM hymns
WHERE book_id = $1
`

func (q *Queries) ListHymnNumbers(ctx context.Context, bookID int64) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listHymnNumbers, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchHymnBook = `-- name: TouchHymnBook :exec
UPDATE hymn_books
SET updated_at = NOW()
WHERE id = $1
`

// A new version of the book: the apps download it again.
func (q *Queries) TouchHymnBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchHymnBook, id)
	return err
}

const updateHymnBook = `-- name: UpdateHymnBook :execrows
UPDATE hymn_books
SET title = $1,
    language = $2,
    position = $3
WHERE id = $4
  AND (title <> $1 OR language <> $2 OR position <> $3)
`

type UpdateHymnBookParams struct {
	Title    string `json:"title"`
	Language string `json:"language"`
	Position int32  `json:"position"`
	ID       int64  `json:"id"`
}

// Only writes when something differs, so the caller knows if the book changed.
func (q *Queries) UpdateHymnBook(ctx context.Context, arg UpdateHymnBookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHymnBook,
		arg.Title,
		arg.Language,
		arg.Position,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertHymn = `-- name: UpsertHymn :execrows
INSERT INTO hymns (book_id, number, title, author, parts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (book_id, number) DO UPDATE
SET title = EXCLUDED.title,
    author = EXCLUDED.author,
    parts = EXCLUDED.parts,
    updated_at = NOW()
WHERE hymns.title IS DISTINCT FROM EXCLUDED.title
   OR hymns.author IS DISTINCT FROM EXCLUDED.author
   OR hymns.parts IS DISTINCT FROM EXCLUDED.parts
`

type UpsertHymnParams struct {
	BookID int64           `json:"book_id"`
	Number int32           `json:"number"`
	Title  string          `json:"title"`
	Author string          `json:"author"`
	Parts  json.RawMessage `json:"parts"`
}

// 1 row when the hymn is new or changed, 0 when it is already identical.
func (q *Queries) UpsertHymn(ctx context.Context, arg UpsertHymnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertHymn,
		arg.BookID,
		arg.Number,
		arg.Title,
		arg.Author,
		arg.Parts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
