// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type User struct {
	ID           int64          `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	HashPassword string         `json:"hash_password"`
	CreatedAt    interface{}    `json:"created_at"`
}
