// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"
	"database/sql"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, birth_date, city, country, church, assembly)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, birth_date, city, country, church, assembly, created_at, updated_at
`

type CreateProfileParams struct {
	UserID    int64          `json:"user_id"`
	BirthDate sql.NullTime   `json:"birth_date"`
	City      sql.NullString `json:"city"`
	Country   sql.NullString `json:"country"`
	Church    sql.NullString `json:"church"`
	Assembly  sql.NullString `json:"assembly"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.UserID,
		arg.BirthDate,
		arg.City,
		arg.Country,
		arg.Church,
		arg.Assembly,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthDate,
		&i.City,
		&i.Country,
		&i.Church,
		&i.Assembly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, user_id, birth_date, city, country, church, assembly, created_at, updated_at FROM profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, userID int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthDate,
		&i.City,
		&i.Country,
		&i.Church,
		&i.Assembly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, user_id, birth_date, city, country, church, assembly, created_at, updated_at FROM profiles
ORDER BY id DESC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthDate,
			&i.City,
			&i.Country,
			&i.Church,
			&i.Assembly,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET birth_date = COALESCE($2, birth_date),
    city = COALESCE($3, city),
    country = COALESCE($4, country),
    church = COALESCE($5, church),
    assembly = COALESCE($6, assembly),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, birth_date, city, country, church, assembly, created_at, updated_at
`

type UpdateProfileParams struct {
	UserID    int64          `json:"user_id"`
	BirthDate sql.NullTime   `json:"birth_date"`
	City      sql.NullString `json:"city"`
	Country   sql.NullString `json:"country"`
	Church    sql.NullString `json:"church"`
	Assembly  sql.NullString `json:"assembly"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.UserID,
		arg.BirthDate,
		arg.City,
		arg.Country,
		arg.Church,
		arg.Assembly,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthDate,
		&i.City,
		&i.Country,
		&i.Church,
		&i.Assembly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
