// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getByPhoneNumber = `-- name: GetByPhoneNumber :one
SELECT id, first_name, last_name, hash_password, created_at, phone_number, email
FROM users
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, first_name, last_name, hash_password, created_at, phone_number, email
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, hash_password, created_at, phone_number, email
FROM users
ORDER BY id DESC
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.HashPassword,
			&i.CreatedAt,
			&i.PhoneNumber,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users(
                  first_name,
                  last_name,
                  phone_number,
                  email,
                  hash_password
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, first_name, last_name, hash_password, created_at, phone_number, email
`

type RegisterUserParams struct {
	FirstName    string         `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	PhoneNumber  string         `json:"phone_number"`
	Email        sql.NullString `json:"email"`
	HashPassword string         `json:"hash_password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, registerUser,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Email,
		arg.HashPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    phone_number = COALESCE($4, phone_number),
    email = COALESCE($5, email),
    hash_password = COALESCE($6, hash_password)
WHERE id = $1
RETURNING id, first_name, last_name, hash_password, created_at, phone_number, email
`

type UpdateUserParams struct {
	ID           int64          `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	PhoneNumber  string         `json:"phone_number"`
	Email        sql.NullString `json:"email"`
	HashPassword string         `json:"hash_password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Email,
		arg.HashPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}
